dist: trusty
sudo: false

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']  
    packages: ['cgroup']
 

language : C

script :
  - free
  - cat /proc/meminfo
  - cgget -n --values-only --variable memory.limit_in_bytes /
  - gcc test.c -o testmem 
  - ./testmem
