dist: trusty
sudo: false

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']  
    packages: ['cgroup-bin','libpopt-dev','g++-7','valgrind']
 

language : C

script :
  - free
  - cat /proc/meminfo
  - cgget -n --values-only --variable memory.limit_in_bytes /
  - gcc test.c -o testmem 
  - ./testmem
  - ./install_ltsmin.sh
  - lts_install_dir/bin/pins2lts-seq --help
  - lts_install_dir/bin/pins2lts-mc --help
  - valgrind --tool=memcheck --read-var-info lts_install_dir/bin/pins2lts-mc --help
  - valgrind --tool=helgrind lts_install_dir/bin/pins2lts-mc --help
  
