dist: trusty
sudo: false

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']  
    packages: ['cgroup-bin','valgrind']
#  'libpopt-dev'

language : C


script :
  - free
  - cat /proc/meminfo
  - cgget -n --values-only --variable memory.limit_in_bytes /
  - gcc test.c -o testmem 
  - ./testmem
  - wget http://rpm5.org/files/popt/popt-1.16.tar.gz
  - tar xvzf popt-1.16.tar.gz
  - cd popt-1.16
  - ./configure CFLAGS='-g -O0'
  - make
  - export LD_LIBRARY_PATH=$PWD/.libs
  - cd ..
  - ./install_ltsmin.sh
  - lts_install_dir/bin/pins2lts-seq --help
  - lts_install_dir/bin/pins2lts-mc --help
  - valgrind --tool=memcheck --read-var-info=yes lts_install_dir/bin/pins2lts-mc --help
  - valgrind --tool=helgrind lts_install_dir/bin/pins2lts-mc --help
  
